apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 172.20.4.27
  share: /data/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
