apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: application-service
  namespace: application
  labels:
    job: application-metrics
    app: service-application
spec:
  ports:
  - name: metrics
    port: 3001
    protocol: TCP
  - name: grpc
    port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    app: app
status:
  loadBalancer: {}
