apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: csi-hostpath-sc-custom2
provisioner: hostpath.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
