apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
        name: my-snapshot
        namespace: test-csi-snapshot
spec:
        volumeSnapshotClassName: csi-snapclass
        source:
                persistentVolumeClaimName:  wp-pv-claim
