apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gateway-service
  namespace: gateway
  labels:
    job: gateway-metrics
    app: service-gateway
spec:
  ports:
  - name: metrics 
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: gateway
status:
  loadBalancer: {}
